services:
  - type: web
    name: url-expander
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    autoDeploy: true
    runtime: node
    region: oregon
    envVars:
      - key: NODE_VERSION
        value: 18
