services:
  - type: web
    name: yt-tg-webhook-v8
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: DEFAULT_URL
        value: "https://youtu.be/BfLPuDRgjPw"
      - key: YT_COOKIES_PATH
        value: "cookies.txt"
